#%RAML 1.0 NamedExample
seatslist:
  -
    slot: morning show
    seat: 42
    row: 'F'
    price: 100
  -
    slot: afternoon show 
    seat: 30
    row: A
    price: 150
  -
    slot: evening
    seat: 10
    row: E
    price: 250