#%RAML 1.0 NamedExample
ticketexample:
    moviename: Bahubali
    theatrename: Gayatri
    timing : 6.30 PM 
    numberofseat: 4
    eticketid: 6776
    seat no: A11,A12,A13,A14
    price: 1000
    Date : 08/12/2021
    applied discount: 40%
